### PR TITLE
Add Registrations Table to /admin/event/[eventID]/[year] route

### PR DESCRIPTION
**Pull request by voctory**
### Changes
- Add the registration table
- Add shadcn files (`/src/components/ui`)
- Merge the shadcn overwrites to `tailwing.config.ts`, `globals.css` files
- Create the admin event route, `/admin/event/[eventID]/[year]`

From [Figma](https://www.figma.com/design/CNLGXpCQswX2i5LgKZp4eV/Web-App-UI-Design---BizTech-2024?node-id=304-782) design

### Out of Scope
Proposing we create new tickets for these:
- Connect backend functionality
- Fuzzy search
- QR Code Scanner
- User pop-up page
- File exports (csv, pdf)
- Attendee vs. Partners vs. Waitlisted Tables
- Fixing the Nav bar to adjust to the page's length
- Sorting by column (ascending / descending)

Not an exhaustive list

### For issues
- https://github.com/ubc-biztech/bt-web-v2/issues/10
- https://github.com/ubc-biztech/bt-web-v2/issues/11

### Testing
Ran `npm run build` - passes for `/admin/event/[eventID]/[year]`
(note: other pages from unrelated commits do not build with Next.js - this is going to prevent us from hosting on Vercel until addressed) 
- `/`
- `/_error: /404`
- `/_error: /500`
- `/layout`

https://github.com/ubc-biztech/bt-web-v2/assets/21225415/e765be2f-66de-4145-a0f0-5cc3675d14a7

### CODE REVIEW

**Comment by voctory** [comment]
Sorry, this is a super long commit + PR but it lays down the foundation for the Registration Table. Hoping future commits are smaller!

**Comment by AllanT102** [comment]
Are you working on the mobile version?

**Comment by bennypc** [comment]
So far LGTM too, thanks victor

**Comment by voctory** [comment]
Hey @AllanT102, mobile-responsiveness should be included in this PR - only problem is that the mobile Nav bar doesn't seem compatible for some reason (see the second half of the video) and I haven't had the opportunity to root cause. Do we want to resolve this before merging?

https://github.com/ubc-biztech/bt-web-v2/assets/21225415/91f65bc7-7447-4e85-8479-86df09f16b8b

**Comment by voctory** [comment]
Ok nevermind, there's a fix for the Registration table rendering with the navigation bar:
- Nav bar is styled as `absolute` or `fixed` on mobile, but it's currently rendered as a layer behind the main component. New commit moves `<Navbar>` below `<main>` so that the Navbar renders a layer in front of `<main>`, overlaying over the main content as intended on mobile
- As a result, I also had to give the desktop nav bar a `fixed` style so that it doesn't appear at the very bottom of the screen after I moved Navbar below main
- The desktop nav bar will sometimes change its height or not have enough height if the `<main>` page is too long, gave it `fixed top-0 left-0 bottom-0` so that it's sticky on the top-left-bottom sides

Commit: https://github.com/ubc-biztech/bt-web-v2/pull/13/commits/7f6911efdd95a88ed18be806aac8f0415856c8e7


https://github.com/ubc-biztech/bt-web-v2/assets/21225415/3c85c11b-6d9e-4788-a092-87e9429bce90

**Comment by AllanT102** [comment]
Nice problem solving, good stuff good to merge

**Review by AllanT102 — APPROVED** [review]

**Pull request merged**
