### PR TITLE
Navbar admin user

### PR DESCRIPTION
**Pull request by isa-leroux448**
🎟️ Ticket: Implement User and Admin Navbar according to [ticket](https://github.com/orgs/ubc-biztech/projects/4?pane=issue&itemId=63649154) and the [figma designs](https://www.figma.com/design/CNLGXpCQswX2i5LgKZp4eV/Web-App-UI-Design---BizTech-2024?node-id=118-344&t=q1PEylMqVw9EeO6m-0).

👷 Changes: Added navbar in layout file that takes in icons and routes from a constants file (Tabs.js). Conditionally renders a hamburger menu on mobile. 

Screenshot 2024-06-17 at 11 08 09 PM
Screenshot 2024-06-17 at 11 08 18 PM
Screenshot 2024-06-17 at 11 07 58 PM
Screenshot 2024-06-17 at 11 06 20 PM

https://github.com/ubc-biztech/bt-web-v2/assets/106799810/bc54247e-8b85-476e-836f-2c1653af373b

### CODE REVIEW

**Comment by AllanT102** [comment]
Don't know why but for me I cant see the dropdown icon on mobile? 
Screenshot 2024-06-21 at 11 18 53 AM

**Comment by AllanT102** [comment]
Looks good to me, but I think @bennypc mentioned to remove the bounce. I can't see the animation bc the menu icon isn't there for me.

**Comment by isa-leroux448** [comment]
Sorry I forgot to upload the updated screenshots. I removed the bounce - it just slides in now. The mobile navbar seems to be working on my iPhone. Wondering what environment you're using @AllanT102? If you're using dev mode did you refresh after setting to mobile mode? The mobile check only happens on initialization so it may not detect mobile if you start off with desktop dimensions then switch to mobile without refreshing.
IMG_4536

https://github.com/ubc-biztech/bt-web-v2/assets/106799810/44b7cf2d-59da-4d32-a01d-e4271c355b08

**Comment by AllanT102** [comment]
Looks good, just move the tabs file to a constants directory

**Review by AllanT102 — APPROVED** [review]

**Pull request merged**
